### ISSUE TITLE
Unable to start Docker on Pi2B

### ISSUE THREAD

**Issue by joopjuh** [petrvlcek/bisecur2mqtt#3]
Hi Petrvlcek,

Thanks for taking the time in creating and sharing this.
I've been running into the following issue when i docker compose up the yaml.
It looks like the code is fetching MQTT_PASSWORD twice instead of the MQTT_USERNAME value.

`[+] Running 1/0
 ⠿ Container bisecur2mqtt  Created                                                                                                                                0.0s
Attaching to bisecur2mqtt
bisecur2mqtt  | 10:43:10.253 [main] DEBUG com.github.petrvlcek.bisecur2mqtt.EnvConfig - Retrieving environment variable: MQTT_SERVER_URI

bisecur2mqtt  | 10:43:10.354 [main] DEBUG com.github.petrvlcek.bisecur2mqtt.EnvConfig - Retrieving environment variable: MQTT_CLIENT_ID

bisecur2mqtt  | 10:43:11.235 [main] DEBUG com.github.petrvlcek.bisecur2mqtt.EnvConfig - Retrieving environment variable: MQTT_PASSWORD

bisecur2mqtt  | 10:43:11.244 [main] DEBUG com.github.petrvlcek.bisecur2mqtt.EnvConfig - Retrieving environment variable: MQTT_PASSWORD

bisecur2mqtt  | Exception in thread "main" org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,primary_type:'org.eclipse.paho.client.mqttv3.MqttClient']
bisecur2mqtt  | 	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
bisecur2mqtt  | 	at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
bisecur2mqtt  | 	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
bisecur2mqtt  | 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
bisecur2mqtt  | 	at org.koin.core.scope.Scope.get(Scope.kt:128)
bisecur2mqtt  | 	at com.github.petrvlcek.bisecur2mqtt.App$special$$inlined$inject$default$1.invoke(Scope.kt:327)
bisecur2mqtt  | 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
bisecur2mqtt  | 	at com.github.petrvlcek.bisecur2mqtt.App.getMqttClient(App.kt:26)
bisecur2mqtt  | 	at com.github.petrvlcek.bisecur2mqtt.App.start(App.kt:29)
bisecur2mqtt  | 	at com.github.petrvlcek.bisecur2mqtt.App$Companion.main(App.kt:13)
bisecur2mqtt  | 	at com.github.petrvlcek.bisecur2mqtt.App.main(App.kt)
bisecur2mqtt  | Caused by: Not authorized to connect (5)
bisecur2mqtt  | 	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
bisecur2mqtt  | 	at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:1053)
bisecur2mqtt  | 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:151)
bisecur2mqtt  | 	at java.lang.Thread.run(Thread.java:750)
bisecur2mqtt exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
`

In the Config.Kt file i noticed this
`    override val mqttUsername by lazy { getRequiredEnv("MQTT_PASSWORD") }`
`    override val mqttPassword by lazy { getRequiredEnv("MQTT_PASSWORD") }`

Could it be that the first line should contain MQTT_USERNAME?

Thanks for looking into this issue.
Cheers,

Blubkens.

**Comment by petrvlcek** [comment]
Thanks for the PR 🙂👍🏼

**Comment by blubkens** [comment]
No problem. 🍻
